### PR TITLE
Don't store generator

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by hobarrera** [comment]
Exactly what impact does this have?

**Comment by untitaker** [comment]
It seems wrong to leave a drained iterator lying around in the instance. We could also remove `self.lists` and dispose of the generator after we're done with it.

**Comment by hobarrera** [comment]
I'd prefer to generate the list before passing it to the constructor, so this doesn't kick us back unexpectedly when we reuse it working on the full interactive interface.

**Comment by untitaker** [comment]
>so this doesn't kick us back unexpectedly when we reuse it working on the full interactive interface.

Yes, this is the reason I made this PR. Why rely on the caller to fulfill contract though?

**Comment by hobarrera** [comment]
> Pull requests that have a failing status can’t be merged on a phone.

**Comment by untitaker** [comment]
Do you approve this PR? It appears only codecov's status fails

**Comment by hobarrera** [comment]
Yes, es. I tried to merge it but Couldn't.

**Pull request merged**
