### PR TITLE
delete cmd: Show tasks that will be deleted

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by hobarrera** [comment]
Tests need to be updated accordingly.

**Comment by untitaker** [comment]
Actually master failed, fixed.

**Comment by hobarrera** [comment]
Thanks for fixing master. This branch still requires a few test updates too.

**Comment by untitaker** [comment]
Ok, it's fixed.

**Comment by hobarrera** [comment]
Thanks!

**Pull request merged**
