### PR TITLE
Shut up the codecov bot

### PR DESCRIPTION
**Pull request by hobarrera**
The bot seems to leave a comment reflecting *the exact same thing* that the check/integration says, so it's completely useless.

### CODE REVIEW

**Comment by hobarrera** [comment]
Apparently, we could disable it at an org level.

**Comment by untitaker** [comment]
Where can we do that?

**Comment by hobarrera** [comment]
It *was* [here](https://github.com/organizations/pimutils/settings/installations), then I removed it (I'd also added it).

**Comment by untitaker** [comment]
I accidentally added the codecov github integration that you removed. I removed it again. 

On 17 February 2017 00:32:22 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>Reopened #105.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/todoman/pull/105#event-965956908

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment]
Oh, okay. Yeah, their instructions are really confusing, I honestly don't understand it.

The integration is the bot, but if you remove it you still get the PR checks. Which I want to keep, but wonder how I'd remove them if I wanted to.

**Pull request closed without merging**
