### PR TITLE
Add 'description' and 'modified_at' attributes to the output of --porcelain

### PR DESCRIPTION
**Pull request by hut**
Add 'description' and 'modified_at' attributes to the output of --porcelain.

Btw, is there a reason why we don't simply add all the attributes of Todo class to the output of porcelain?

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Looks good, but some tests need updating since they fail due the the [unexpected] new fields.

Can you update those, please?

Let me know if you've any questions about them, or how to run them locally. Thanks!

**Comment by hut** [comment]
Sure thing, will update them

**Comment by hut** [comment]
Sorry for the delay, this was kinda low prio, but here are the updated test cases. :)

Happy holidays.

**Comment by reactorcoremeltdown** [comment]
Hi everyone!

I'd really like to get this change merged into the upstream. I have patched this up already inside my custom docker container with todoman, mainly because I rely on some automation that uses description field.

Is there anything I could help you with? This is not urgent by any far stretch, and I hugely appreciate your time and effort!

Thanks :)

**Pull request merged**
