### PR TITLE
Fix master

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Clean up a flake8 failure. No idea how this got into master.

Also update the changelog, since I had this change just locally, for some reason :man_shrugging:

### CODE REVIEW

**Comment by penguineer** [comment]
Will this fix the test problems in #329?

**Comment by WhyNotHugo** [comment]
That's my intention, but python is failing to install on macOS, and I can't quite figure out how to get around it.

To make things worse, Jenkins macOS builds take AGES, so this is quite time-consuming to debug. :(

But yes, `master` is currently broken, and the failures on #329 are because of these failures.

**Comment by penguineer** [comment]
Is there a way to help with this issue?

**Comment by penguineer** [comment]
7425dd7 actually made me lol  :D

**Comment by WhyNotHugo** [comment]
Opened #335 to track macOS failures separately.

**Pull request merged**
