### PR TITLE
Restore  behavior of interactivity

### PR DESCRIPTION
**Pull request by untitaker**
The current behavior is not very erogonomic IMO

### CODE REVIEW

**Comment by untitaker** [comment]
No idea why the Travis build fails.

**Comment by hobarrera** [comment]
Could you clarify what this changes? It's not obvious to me, sorry.

Travis seemed to have some internal hiccup, I've told it to retry, and I think it's safe to ignore the failure.

**Comment by untitaker** [comment]
I used to be able to run `todo edit 10` to edit task 10 interactively. I removed this ability in #52 for consistency with `new` (you have to pass `-i` to enter interactive mode) but I find this behavior much more useful. We can debate whether we should use this behavior fo `new` as well.

**Comment by untitaker** [comment]
@hobarrera Any update on this?

**Comment by hobarrera** [comment]
Sorry, only just got around to trying this.

This makes sense, but I also think it makes sense for `new` to open interactive mode if no arguments are provided (for consistency).

**Comment by untitaker** [comment]
Done!

**Comment by hobarrera** [comment]
Tests seem to be failing :(

**Comment by untitaker** [comment]
Now they don't

**Comment by hobarrera** [comment]
LGTM, feel free to merge this in. 🚀

**Pull request merged**
