### PR TITLE
Programmatically generate output of --help

### PR DESCRIPTION
**Pull request by hobarrera**
The docs include the output of `todo --help`, but it was a copy-paste
which easily went out of date.

Include this output programmatically by actually running `todo --help`.

---

This PR is blocked by [this](https://bitbucket.org/birkenfeld/sphinx-contrib/pull-requests/130/) upstream issue, and cannot be merged until that issue is merged+released.

### CODE REVIEW

**Comment by hobarrera** [comment]
Upstream seems unresponsive, so I'll just fork that if there's no reply soon.

**Comment by untitaker** [comment]
I'd ask in the IRC channel if they would move that repo to GitHub, as they've done with the main Sphinx one.

**Comment by hobarrera** [comment]
Oddly, it seems that other PRs have had some attention. sphinx-contrib doesn't seem to be official supported either, so I don't know what their stance towards it would be.

**Comment by hobarrera** [comment]
I've updated the PR, and it should be working now.

I've added requirements-dev, since readthedocs.org will use this (as well as installing via `setup.py install`) before generating the docs.

I've also added a CI task to test the docs, so we can make sure PRs don't brake them *before* merging into master.

**Pull request merged**
