### PR TITLE
OS X

### PR DESCRIPTION
**Pull request by hobarrera**
Two **tests** are failing, which might we worth looking into. CI is actually running :tada:

### CODE REVIEW

**Comment by untitaker** [comment]
I suspect low mtime-precision, like in khal.

**Comment by hobarrera** [comment]
**Thank you**, I'd never thought of that! I'll add some mechanism to for cache invalidation for this sort of thing and add it to these tests (basically, force a reload).

**Comment by untitaker** [comment]
What about copying the `min_sleep_time` fixture from khal?

**Comment by hobarrera** [comment]
That fixture makes sense to test natural cache expiration, but I don't want to include that everywhere. For most tests, cache invalidation and sleeping is a bit out of scope and I want to force a reload.

I **will** add new tests to make sure we expire the cache properly, and all that mtime fuzz.

**Comment by hobarrera** [comment]
Maybe what I **really** want is a `load_todos` fixture, instead of calling `default_database.update_cache(); list(default_database.todos())` in half of the tests.

**Comment by hobarrera** [comment]
:tada:

**Comment by hobarrera** [comment]
These failure must be a fluke; that diff only changes the README.

**Pull request merged**
