### PR TITLE
Implement --humanize

### LINKED ISSUE #128: Humanize all date times?
I'd like to evaluate humanizing all date times (probably with [humanize](https://github.com/jmoiron/humanize)).

* Not the default (due to loss of precision).
* Probably some `-h/--humanize` flag.

We'd have to look at pitfalls, and potential issues that may be a bit non-obvious.

### LINKED ISSUE #159: `todo --porcelain edit ...` crashes
When providing todoman with the porcelain option, the TodoEditor crashes. This can be fixed together with https://github.com/pimutils/todoman/issues/158 by not relying on `ctx.obj["formatter"]` at all.

### PR DESCRIPTION
**Pull request by hobarrera**
* [x] Tests
* [ ] Tests
* [ ] Tests

Fixes #159 
Closes #128

### CODE REVIEW

**Comment by untitaker** [comment]
`TodoFormatter` already has code for humanizing datetimes. What about that?

**Comment by hobarrera** [comment]
The main difference is that the existing code merely replaces a date with "tomorrow", making it more readable but with no loss in precision. The `HumanizedFormatter` has output with less precision, and exact dates/times are lost.

**Comment by untitaker** [comment]
My point is that it's not very intuitive for humanized datetimes to be shown when `--humanized` is not used.

**Comment by hobarrera** [comment]
Yeah, I agree with that. Maybe the docs could cover that a bit? Do you have any other suggestion?

A second choice is to rename `--humanize` to `--fuzzy`.

**Comment by untitaker** [comment]
Why not just remove the humanizing code from the default formatter?

**Comment by hobarrera** [comment]
> Why not just remove the humanizing code from the default formatter?

Don't really see why. :(

**Comment by untitaker** [comment]
I mean that only when `--humanize` is used, the date is replaced with `Today` and so on. I.e. remove the special datetimes dict and all that.

**Comment by hobarrera** [comment]
Nope, I don't think I understand.

**Comment by untitaker** [comment]
With this PR we have two ways to humanize datetimes, once using `humanize`, once using #108. I think there's no major difference between being precise or not. The bigger difference is between formatting with the normal `date_format` from the config... and not doing that.

**Comment by hobarrera** [comment]
I'm not sure if you dislike the result or the implementation (or both).

**Comment by untitaker** [comment]
The intended UI

**Comment by hobarrera** [comment]
So, would you rather not show "Tomorrow/"Today" in non-humanized form (for the basic formatter)? Or do you dislike this PR entirely?

What would you change for it?

**Comment by untitaker** [comment]
When `humanize` setting is false, don't use the strings "Today" or "Tomorrow"
at all, i.e. use pre-#108 behavior.

Otherwise use the humanize package.

**Comment by hobarrera** [comment]
> When `humanize` setting is false, don't use the strings "Today" or "Tomorrow" at all, i.e. use pre-#108 behavior.

Why do you feel that's a bad idea? (I'm honestly just trying to understand your POV).

**Comment by untitaker** [comment]
I'm not sure how to express it better: It feels bad to have two implementations
for humanizing datetimes, first #108 and now using the `humanize` pkg. Two
implementations that basically serve the same purpose (again I don't consider
the distinction "fuzzy" vs "exact" important). IMO one of them has to go.

**Comment by hobarrera** [comment]
PR updated (and a lot has been rewritten).

**Comment by untitaker** [comment]
This reintroduces the bug #160 fixed, because now we might end up using humanized datetimes inside TodoEditor again.

**Comment by hobarrera** [comment]
Oh, you're right; I just need to modify `formatter` and never `ui_formatter`, right?

**Comment by untitaker** [comment]
Right, but we could also stick closer to the original design and have only two `TodoFormatters`, with formatting methods having a `humanize` flag.

**Comment by hobarrera** [comment]
> Right, but we could also stick closer to the original design and have only two TodoFormatters, with formatting methods having a humanize flag.

I think this is actually a perfect scenario to have to classes because we have perfect polymorphism: both implement the same API, but have different implementations.

**Comment by untitaker** [comment]
In either case you're now mixing two approaches: You're passing `porcelain` as a flag instead of `formatter_class=PorcelainFormatter`, at the same time you don't pass `humanize` but influence behavior using `formatter_class`.

**Comment by hobarrera** [comment]
Yup, that's ugly. Updated.

**Comment by hobarrera** [comment]
I prefer `DefaultFormatter` because it's also the one used by default and that makes it a wee bit more obvious.

Regarding the property names: I think they're quite representative, but I'm open to better suggestions.

**Comment by hobarrera** [comment]
Rebased. I actually found another bug we had hiding there (which was made evident due to the merge), so I fixed it and added a few tests.

**Pull request merged**
