### PR TITLE
Don't strip time from datetime objects

### PR DESCRIPTION
**Pull request by untitaker**
If I have a task at 7pm and it's 11am, todoman currently shows that task
as red since it's at the same date. This patch prevents this.

### CODE REVIEW

**Comment by untitaker** [comment]
BTW, `issubclass(datetime, date)`

**Comment by hobarrera** [comment]
Nice catch. LGTM, though please rebase to master, rather than merging master into your branch.

**Comment by untitaker** [comment]
Squash in GitHub UI fixes this

**Comment by hobarrera** [comment]
Oh, right. Feel free to merge this, unless you're planning on adding tests for this.

**Comment by hobarrera** [comment]
LGTM. Feel free to squash-merge this.

**Comment by untitaker** [comment]
Waiting for CI

**Pull request merged**
